name: "Detect secrets with Talisman"
description: "Scan an incoming range of commits for accidentally added secrets and sensitive information"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git
      shell: bash
    - name: Download Talisman
      run: |
        curl -L -o talisman https://github.com/thoughtworks/talisman/releases/download/v1.37.0/talisman_linux_amd64
        chmod +x talisman
      shell: bash
    - name: Configure git safe directory
      run: git config --global --add safe.directory $PWD
      shell: bash
    - name: Run Talisman on push
      if: ${{ github.event_name == 'push' }}
      run: |
        LOCAL_REF="${{ github.ref }}"
        LOCAL_SHA="${{ github.event.after }}"
        REMOTE_REF="${{ github.ref }}"
        REMOTE_SHA="${{ github.event.before }}"
        echo "$LOCAL_REF $LOCAL_SHA $REMOTE_REF $REMOTE_SHA" | ./talisman --githook pre-push
      shell: bash
    - name: Run Talisman in Pull Request
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        LOCAL_REF="refs/heads/${{ github.head_ref }}"
        LOCAL_SHA="${{ github.event.pull_request.head.sha }}"
        REMOTE_REF="refs/heads/${{ github.base_ref }}"
        REMOTE_SHA="${{ github.event.pull_request.base.sha }}"
        echo "$LOCAL_REF $LOCAL_SHA $REMOTE_REF $REMOTE_SHA" | ./talisman --githook pre-push
      shell: bash

branding:
  icon: "lock"
  color: "yellow"
